//! Contains the `Region` enum and its associated traits. It is used to specify
//! a country in which Google Maps has been officially launched. Google's
//! _regions_ uses ccTLDs rather than ISO 3166 country codes. _This is not a
//! comprehensive list of countries, it is a list of countries that Google Maps
//! supports._

use crate::error::Error;
use phf::phf_map;
use serde::{Deserialize, Serialize};

// -----------------------------------------------------------------------------

/// Specifies the region bias.
///
/// [Region Biasing](https://developers.google.com/maps/documentation/directions/intro#RegionBiasing)
/// =================================================================================================
///
/// You can set the Directions service to return results from a specific region
/// by using the `region` parameter. This parameter takes a
/// [ccTLD](https://en.wikipedia.org/wiki/CcTLD) (country code top-level domain)
/// argument specifying the region bias. Most ccTLD codes are identical to ISO
/// 3166-1 codes, with some notable exceptions. For example, the United
/// Kingdom's ccTLD is "uk" (`.co.uk`) while its ISO 3166-1 code is "gb"
/// (technically for the entity of "The United Kingdom of Great Britain and
/// Northern Ireland").
///
/// You may utilize any domain in which the main Google Maps application has
/// launched driving directions.
///
/// For example, a directions request for "Toledo" to "Madrid" returns
/// appropriate results when `region` is set to `es` and "Toledo" is then
/// interpreted as the Spanish city:
///
/// ```
/// https://maps.googleapis.com/maps/api/directions/json?
/// origin=Toledo&destination=Madrid
/// &region=es
/// &key=YOUR_API_KEY
///
/// {
///     "status": "OK",
///     "routes": [ {
///         "summary": "AP-41",
///         "legs": [ {
///             ...
///         } ],
///         "copyrights": "Map data ©2010 Europa Technologies, Tele Atlas",
///         "warnings": [ ],
///         "waypoint_order": [ ]
///     } ]
/// }
/// ```
///
/// A directions request for "Toledo" to "Madrid" sent without a `region`
/// parameter does not return results, because "Toledo" is interpreted as the
/// city in Ohio and not Spain:
///
/// ```
/// https://maps.googleapis.com/maps/api/directions/json?
/// origin=Toledo&destination=Madrid
/// &key=YOUR_API_KEY
///
/// {
///     "status": "ZERO_RESULTS",
///     "routes": [ ]
/// }
/// ```
///
/// [Map Coverage Details](https://developers.google.com/maps/coverage)
/// ===================================================================
///
/// The Google Maps team is constantly working to improve our international
/// coverage. Some data, such as public transit routes, are available at a city
/// level and do not appear in this list. Please note that data coverage can
/// change if licensing agreements with the data providers change.

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize, Deserialize)]
pub enum Region {
    AlandIslands,
    Afghanistan,
    Albania,
    Algeria,
    AmericanSamoa,
    Andorra,
    Angola,
    Anguilla,
    Antarctica,
    AntiguaAndBarbuda,
    Argentina,
    Armenia,
    Aruba,
    AscensionIsland,
    Australia,
    Austria,
    Azerbaijan,
    Bahamas,
    Bahrain,
    Bangladesh,
    Barbados,
    Belarus,
    Belgium,
    Belize,
    Benin,
    Bermuda,
    Bhutan,
    Bolivia,
    BosniaAndHerzegovina,
    Botswana,
    BouvetIsland,
    Brazil,
    BritishIndianOceanTerritory,
    BritishVirginIslands,
    Brunei,
    Bulgaria,
    BurkinaFaso,
    Burundi,
    Cambodia,
    Cameroon,
    Canada,
    CanaryIslands,
    CapeVerde,
    CaribbeanNetherlands,
    CaymanIslands,
    CentralAfricanRepublic,
    CeutaAndMelilla,
    Chad,
    Chile,
    China,
    ChristmasIsland,
    ClippertonIsland,
    CocosKeelingIslands,
    Colombia,
    Comoros,
    CongoBrazzaville,
    CongoKinshasa,
    CookIslands,
    CostaRica,
    CotedIvoire,
    Croatia,
    Cuba,
    Curacao,
    Cyprus,
    Czechia,
    Denmark,
    DiegoGarcia,
    Djibouti,
    Dominica,
    DominicanRepublic,
    Ecuador,
    Egypt,
    ElSalvador,
    EquatorialGuinea,
    Eritrea,
    Estonia,
    Eswatini,
    Ethiopia,
    FalklandIslands,
    FaroeIslands,
    Fiji,
    Finland,
    France,
    FrenchGuiana,
    FrenchPolynesia,
    FrenchSouthernTerritories,
    Gabon,
    Gambia,
    Georgia,
    Germany,
    Ghana,
    Gibraltar,
    Greece,
    Greenland,
    Grenada,
    Guadeloupe,
    Guam,
    Guatemala,
    Guernsey,
    Guinea,
    GuineaBissau,
    Guyana,
    Haiti,
    HeardAndMcDonaldIslands,
    Honduras,
    HongKong,
    Hungary,
    Iceland,
    India,
    Indonesia,
    Iran,
    Iraq,
    Ireland,
    IsleOfMan,
    Israel,
    Italy,
    Jamaica,
    Japan,
    Jersey,
    Jordan,
    Kazakhstan,
    Kenya,
    Kiribati,
    Kosovo,
    Kuwait,
    Kyrgyzstan,
    Laos,
    Latvia,
    Lebanon,
    Lesotho,
    Liberia,
    Libya,
    Liechtenstein,
    Lithuania,
    Luxembourg,
    Macao,
    Madagascar,
    Malawi,
    Malaysia,
    Maldives,
    Mali,
    Malta,
    MarshallIslands,
    Martinique,
    Mauritania,
    Mauritius,
    Mayotte,
    Mexico,
    Micronesia,
    Moldova,
    Monaco,
    Mongolia,
    Montenegro,
    Montserrat,
    Morocco,
    Mozambique,
    Myanmar,
    Namibia,
    Nauru,
    Nepal,
    Netherlands,
    NewCaledonia,
    NewZealand,
    Nicaragua,
    Niger,
    Nigeria,
    Niue,
    NorfolkIsland,
    NorthKorea,
    NorthMacedonia,
    NorthernMarianaIslands,
    Norway,
    Oman,
    Pakistan,
    Palau,
    Palestine,
    Panama,
    PapuaNewGuinea,
    Paraguay,
    Peru,
    Philippines,
    PitcairnIslands,
    Poland,
    Portugal,
    PuertoRico,
    Qatar,
    Romania,
    Russia,
    Rwanda,
    Reunion,
    Samoa,
    SanMarino,
    SaudiArabia,
    Senegal,
    Serbia,
    Seychelles,
    SierraLeone,
    Singapore,
    SintMaarten,
    Slovakia,
    Slovenia,
    SolomonIslands,
    Somalia,
    SouthAfrica,
    SouthGeorgiaAndTheSouthSandwichIslands,
    SouthKorea,
    SouthSudan,
    Spain,
    SriLanka,
    StBarthelemy,
    StHelena,
    StKittsAndNevis,
    StLucia,
    StMartin,
    StPierreAndMiquelon,
    StVincentAndGrenadines,
    Sudan,
    Suriname,
    SvalbardAndJanMayen,
    Sweden,
    Switzerland,
    Syria,
    SaoTomeAndPrincipe,
    Taiwan,
    Tajikistan,
    Tanzania,
    Thailand,
    TimorLeste,
    Togo,
    Tokelau,
    Tonga,
    TrinidadAndTobago,
    TristanDaCunha,
    Tunisia,
    Turkey,
    Turkmenistan,
    TurksAndCaicosIslands,
    Tuvalu,
    USOutlyingIslands,
    USVirginIslands,
    Uganda,
    Ukraine,
    UnitedArabEmirates,
    UnitedKingdom,
    UnitedStates,
    Uruguay,
    Uzbekistan,
    Vanuatu,
    VaticanCity,
    Venezuela,
    Vietnam,
    WallisAndFutuna,
    WesternSahara,
    Yemen,
    Zambia,
    Zimbabwe,
} // enum

// -----------------------------------------------------------------------------

impl std::convert::From<&Region> for String {
    /// Converts a `Region` enum to a `String` that contains a
    /// [region](https://developers.google.com/maps/coverage) code.
    fn from(region: &Region) -> String {
        match region {
            Region::AlandIslands => String::from("ax"),
            Region::Afghanistan => String::from("af"),
            Region::Albania => String::from("al"),
            Region::Algeria => String::from("dz"),
            Region::AmericanSamoa => String::from("as"),
            Region::Andorra => String::from("ad"),
            Region::Angola => String::from("ao"),
            Region::Anguilla => String::from("ai"),
            Region::Antarctica => String::from("aq"),
            Region::AntiguaAndBarbuda => String::from("aq"),
            Region::Argentina => String::from("ar"),
            Region::Armenia => String::from("am"),
            Region::Aruba => String::from("aw"),
            Region::AscensionIsland => String::from("ac"),
            Region::Australia => String::from("au"),
            Region::Austria => String::from("at"),
            Region::Azerbaijan => String::from("az"),
            Region::Bahamas => String::from("bs"),
            Region::Bahrain => String::from("bh"),
            Region::Bangladesh => String::from("bd"),
            Region::Barbados => String::from("bb"),
            Region::Belarus => String::from("by"),
            Region::Belgium => String::from("be"),
            Region::Belize => String::from("bz"),
            Region::Benin => String::from("bj"),
            Region::Bermuda => String::from("bj"),
            Region::Bhutan => String::from("bt"),
            Region::Bolivia => String::from("bo"),
            Region::BosniaAndHerzegovina => String::from("ba"),
            Region::Botswana => String::from("ba"),
            Region::BouvetIsland => String::from("bv"),
            Region::Brazil => String::from("br"),
            Region::BritishIndianOceanTerritory => String::from("io"),
            Region::BritishVirginIslands => String::from("vg"),
            Region::Brunei => String::from("bn"),
            Region::Bulgaria => String::from("bg"),
            Region::BurkinaFaso => String::from("bf"),
            Region::Burundi => String::from("bi"),
            Region::Cambodia => String::from("kh"),
            Region::Cameroon => String::from("cm"),
            Region::Canada => String::from("ca"),
            Region::CanaryIslands => String::from("ic"),
            Region::CapeVerde => String::from("cv"),
            Region::CaribbeanNetherlands => String::from("bq"),
            Region::CaymanIslands => String::from("ky"),
            Region::CentralAfricanRepublic => String::from("cf"),
            Region::CeutaAndMelilla => String::from("ea"),
            Region::Chad => String::from("td"),
            Region::Chile => String::from("cl"),
            Region::China => String::from("cn"),
            Region::ChristmasIsland => String::from("cx"),
            Region::ClippertonIsland => String::from("cp"),
            Region::CocosKeelingIslands => String::from("cc"),
            Region::Colombia => String::from("co"),
            Region::Comoros => String::from("km"),
            Region::CongoBrazzaville => String::from("cg"),
            Region::CongoKinshasa => String::from("cd"),
            Region::CookIslands => String::from("ck"),
            Region::CostaRica => String::from("cr"),
            Region::CotedIvoire => String::from("ci"),
            Region::Croatia => String::from("hr"),
            Region::Cuba => String::from("cu"),
            Region::Curacao => String::from("cw"),
            Region::Cyprus => String::from("cy"),
            Region::Czechia => String::from("cz"),
            Region::Denmark => String::from("dk"),
            Region::DiegoGarcia => String::from("dg"),
            Region::Djibouti => String::from("dj"),
            Region::Dominica => String::from("dm"),
            Region::DominicanRepublic => String::from("do"),
            Region::Ecuador => String::from("ec"),
            Region::Egypt => String::from("eg"),
            Region::ElSalvador => String::from("sv"),
            Region::EquatorialGuinea => String::from("gq"),
            Region::Eritrea => String::from("er"),
            Region::Estonia => String::from("ee"),
            Region::Eswatini => String::from("sz"),
            Region::Ethiopia => String::from("et"),
            Region::FalklandIslands => String::from("fk"),
            Region::FaroeIslands => String::from("fo"),
            Region::Fiji => String::from("fj"),
            Region::Finland => String::from("fi"),
            Region::France => String::from("fr"),
            Region::FrenchGuiana => String::from("gf"),
            Region::FrenchPolynesia => String::from("pf"),
            Region::FrenchSouthernTerritories => String::from("tf"),
            Region::Gabon => String::from("ga"),
            Region::Gambia => String::from("gm"),
            Region::Georgia => String::from("ge"),
            Region::Germany => String::from("de"),
            Region::Ghana => String::from("gh"),
            Region::Gibraltar => String::from("gi"),
            Region::Greece => String::from("gr"),
            Region::Greenland => String::from("gl"),
            Region::Grenada => String::from("gd"),
            Region::Guadeloupe => String::from("gd"),
            Region::Guam => String::from("gu"),
            Region::Guatemala => String::from("gt"),
            Region::Guernsey => String::from("gg"),
            Region::Guinea => String::from("gn"),
            Region::GuineaBissau => String::from("gw"),
            Region::Guyana => String::from("gy"),
            Region::Haiti => String::from("ht"),
            Region::HeardAndMcDonaldIslands => String::from("hm"),
            Region::Honduras => String::from("hn"),
            Region::HongKong => String::from("hn"),
            Region::Hungary => String::from("hu"),
            Region::Iceland => String::from("is"),
            Region::India => String::from("in"),
            Region::Indonesia => String::from("id"),
            Region::Iran => String::from("ir"),
            Region::Iraq => String::from("iq"),
            Region::Ireland => String::from("ie"),
            Region::IsleOfMan => String::from("im"),
            Region::Israel => String::from("il"),
            Region::Italy => String::from("it"),
            Region::Jamaica => String::from("jm"),
            Region::Japan => String::from("jm"),
            Region::Jersey => String::from("je"),
            Region::Jordan => String::from("jo"),
            Region::Kazakhstan => String::from("kz"),
            Region::Kenya => String::from("ke"),
            Region::Kiribati => String::from("ki"),
            Region::Kosovo => String::from("xk"),
            Region::Kuwait => String::from("kw"),
            Region::Kyrgyzstan => String::from("kg"),
            Region::Laos => String::from("kg"),
            Region::Latvia => String::from("lv"),
            Region::Lebanon => String::from("lb"),
            Region::Lesotho => String::from("ls"),
            Region::Liberia => String::from("lr"),
            Region::Libya => String::from("ly"),
            Region::Liechtenstein => String::from("li"),
            Region::Lithuania => String::from("lt"),
            Region::Luxembourg => String::from("lu"),
            Region::Macao => String::from("mo"),
            Region::Madagascar => String::from("mg"),
            Region::Malawi => String::from("mw"),
            Region::Malaysia => String::from("my"),
            Region::Maldives => String::from("mv"),
            Region::Mali => String::from("ml"),
            Region::Malta => String::from("mt"),
            Region::MarshallIslands => String::from("mt"),
            Region::Martinique => String::from("mq"),
            Region::Mauritania => String::from("mr"),
            Region::Mauritius => String::from("mu"),
            Region::Mayotte => String::from("yt"),
            Region::Mexico => String::from("mx"),
            Region::Micronesia => String::from("fm"),
            Region::Moldova => String::from("md"),
            Region::Monaco => String::from("mc"),
            Region::Mongolia => String::from("mn"),
            Region::Montenegro => String::from("me"),
            Region::Montserrat => String::from("ms"),
            Region::Morocco => String::from("ma"),
            Region::Mozambique => String::from("ma"),
            Region::Myanmar => String::from("mm"),
            Region::Namibia => String::from("na"),
            Region::Nauru => String::from("nr"),
            Region::Nepal => String::from("np"),
            Region::Netherlands => String::from("nl"),
            Region::NewCaledonia => String::from("nc"),
            Region::NewZealand => String::from("nc"),
            Region::Nicaragua => String::from("ni"),
            Region::Niger => String::from("ne"),
            Region::Nigeria => String::from("ng"),
            Region::Niue => String::from("nu"),
            Region::NorfolkIsland => String::from("nf"),
            Region::NorthKorea => String::from("kp"),
            Region::NorthMacedonia => String::from("mk"),
            Region::NorthernMarianaIslands => String::from("mp"),
            Region::Norway => String::from("no"),
            Region::Oman => String::from("om"),
            Region::Pakistan => String::from("pk"),
            Region::Palau => String::from("pk"),
            Region::Palestine => String::from("ps"),
            Region::Panama => String::from("pa"),
            Region::PapuaNewGuinea => String::from("pg"),
            Region::Paraguay => String::from("pg"),
            Region::Peru => String::from("pe"),
            Region::Philippines => String::from("ph"),
            Region::PitcairnIslands => String::from("pn"),
            Region::Poland => String::from("pl"),
            Region::Portugal => String::from("pt"),
            Region::PuertoRico => String::from("pr"),
            Region::Qatar => String::from("pr"),
            Region::Romania => String::from("ro"),
            Region::Russia => String::from("ru"),
            Region::Rwanda => String::from("rw"),
            Region::Reunion => String::from("re"),
            Region::Samoa => String::from("ws"),
            Region::SanMarino => String::from("sm"),
            Region::SaudiArabia => String::from("sa"),
            Region::Senegal => String::from("sn"),
            Region::Serbia => String::from("rs"),
            Region::Seychelles => String::from("sc"),
            Region::SierraLeone => String::from("sl"),
            Region::Singapore => String::from("sg"),
            Region::SintMaarten => String::from("sx"),
            Region::Slovakia => String::from("sk"),
            Region::Slovenia => String::from("si"),
            Region::SolomonIslands => String::from("sb"),
            Region::Somalia => String::from("so"),
            Region::SouthAfrica => String::from("za"),
            Region::SouthGeorgiaAndTheSouthSandwichIslands => String::from("gs"),
            Region::SouthKorea => String::from("kr"),
            Region::SouthSudan => String::from("ss"),
            Region::Spain => String::from("es"),
            Region::SriLanka => String::from("lk"),
            Region::StBarthelemy => String::from("bl"),
            Region::StHelena => String::from("sh"),
            Region::StKittsAndNevis => String::from("kn"),
            Region::StLucia => String::from("lc"),
            Region::StMartin => String::from("mf"),
            Region::StPierreAndMiquelon => String::from("pm"),
            Region::StVincentAndGrenadines => String::from("vc"),
            Region::Sudan => String::from("sd"),
            Region::Suriname => String::from("sr"),
            Region::SvalbardAndJanMayen => String::from("sj"),
            Region::Sweden => String::from("se"),
            Region::Switzerland => String::from("ch"),
            Region::Syria => String::from("sy"),
            Region::SaoTomeAndPrincipe => String::from("st"),
            Region::Taiwan => String::from("tw"),
            Region::Tajikistan => String::from("tj"),
            Region::Tanzania => String::from("tz"),
            Region::Thailand => String::from("th"),
            Region::TimorLeste => String::from("tl"),
            Region::Togo => String::from("tl"),
            Region::Tokelau => String::from("tk"),
            Region::Tonga => String::from("to"),
            Region::TrinidadAndTobago => String::from("tt"),
            Region::TristanDaCunha => String::from("ta"),
            Region::Tunisia => String::from("tn"),
            Region::Turkey => String::from("tr"),
            Region::Turkmenistan => String::from("tm"),
            Region::TurksAndCaicosIslands => String::from("tc"),
            Region::Tuvalu => String::from("tv"),
            Region::USOutlyingIslands => String::from("um"),
            Region::USVirginIslands => String::from("vi"),
            Region::Uganda => String::from("ug"),
            Region::Ukraine => String::from("ua"),
            Region::UnitedArabEmirates => String::from("ae"),
            Region::UnitedKingdom => String::from("co.uk"),
            Region::UnitedStates => String::from("us"),
            Region::Uruguay => String::from("uy"),
            Region::Uzbekistan => String::from("uz"),
            Region::Vanuatu => String::from("vu"),
            Region::VaticanCity => String::from("va"),
            Region::Venezuela => String::from("ve"),
            Region::Vietnam => String::from("vn"),
            Region::WallisAndFutuna => String::from("wf"),
            Region::WesternSahara => String::from("eh"),
            Region::Yemen => String::from("ye"),
            Region::Zambia => String::from("zm"),
            Region::Zimbabwe => String::from("zw"),
        } // match
    } // fn
} // impl

// -----------------------------------------------------------------------------

static REGIONS_BY_CODE: phf::Map<&'static str, Region> = phf_map! {
    "af" => Region::Afghanistan,
    "al" => Region::Albania,
    "dz" => Region::Algeria,
    "as" => Region::AmericanSamoa,
    "ad" => Region::Andorra,
    "ao" => Region::Angola,
    "ai" => Region::Anguilla,
    "aq" => Region::Antarctica,
    "ag" => Region::AntiguaAndBarbuda,
    "ar" => Region::Argentina,
    "am" => Region::Armenia,
    "aw" => Region::Aruba,
    "ac" => Region::AscensionIsland,
    "au" => Region::Australia,
    "at" => Region::Austria,
    "az" => Region::Azerbaijan,
    "bs" => Region::Bahamas,
    "bh" => Region::Bahrain,
    "bd" => Region::Bangladesh,
    "bb" => Region::Barbados,
    "by" => Region::Belarus,
    "be" => Region::Belgium,
    "bz" => Region::Belize,
    "bj" => Region::Benin,
    "bm" => Region::Bermuda,
    "bt" => Region::Bhutan,
    "bo" => Region::Bolivia,
    "ba" => Region::BosniaAndHerzegovina,
    "bw" => Region::Botswana,
    "bv" => Region::BouvetIsland,
    "br" => Region::Brazil,
    "io" => Region::BritishIndianOceanTerritory,
    "vg" => Region::BritishVirginIslands,
    "bn" => Region::Brunei,
    "bg" => Region::Bulgaria,
    "bf" => Region::BurkinaFaso,
    "bi" => Region::Burundi,
    "kh" => Region::Cambodia,
    "cm" => Region::Cameroon,
    "ca" => Region::Canada,
    "ic" => Region::CanaryIslands,
    "cv" => Region::CapeVerde,
    "bq" => Region::CaribbeanNetherlands,
    "ky" => Region::CaymanIslands,
    "cf" => Region::CentralAfricanRepublic,
    "ea" => Region::CeutaAndMelilla,
    "td" => Region::Chad,
    "cl" => Region::Chile,
    "cn" => Region::China,
    "cx" => Region::ChristmasIsland,
    "cp" => Region::ClippertonIsland,
    "cc" => Region::CocosKeelingIslands,
    "co" => Region::Colombia,
    "km" => Region::Comoros,
    "cg" => Region::CongoBrazzaville,
    "cd" => Region::CongoKinshasa,
    "ck" => Region::CookIslands,
    "cr" => Region::CostaRica,
    "ci" => Region::CotedIvoire,
    "hr" => Region::Croatia,
    "cu" => Region::Cuba,
    "cw" => Region::Curacao,
    "cy" => Region::Cyprus,
    "cz" => Region::Czechia,
    "dk" => Region::Denmark,
    "dg" => Region::DiegoGarcia,
    "dj" => Region::Djibouti,
    "dm" => Region::Dominica,
    "do" => Region::DominicanRepublic,
    "ec" => Region::Ecuador,
    "eg" => Region::Egypt,
    "sv" => Region::ElSalvador,
    "gq" => Region::EquatorialGuinea,
    "er" => Region::Eritrea,
    "ee" => Region::Estonia,
    "sz" => Region::Eswatini,
    "et" => Region::Ethiopia,
    "fk" => Region::FalklandIslands,
    "fo" => Region::FaroeIslands,
    "fj" => Region::Fiji,
    "fi" => Region::Finland,
    "fr" => Region::France,
    "gf" => Region::FrenchGuiana,
    "pf" => Region::FrenchPolynesia,
    "tf" => Region::FrenchSouthernTerritories,
    "ga" => Region::Gabon,
    "gm" => Region::Gambia,
    "ge" => Region::Georgia,
    "de" => Region::Germany,
    "gh" => Region::Ghana,
    "gi" => Region::Gibraltar,
    "gr" => Region::Greece,
    "gl" => Region::Greenland,
    "gd" => Region::Grenada,
    "gp" => Region::Guadeloupe,
    "gu" => Region::Guam,
    "gt" => Region::Guatemala,
    "gg" => Region::Guernsey,
    "gn" => Region::Guinea,
    "gw" => Region::GuineaBissau,
    "gy" => Region::Guyana,
    "ht" => Region::Haiti,
    "hm" => Region::HeardAndMcDonaldIslands,
    "hn" => Region::Honduras,
    "hk" => Region::HongKong,
    "hu" => Region::Hungary,
    "is" => Region::Iceland,
    "in" => Region::India,
    "id" => Region::Indonesia,
    "ir" => Region::Iran,
    "iq" => Region::Iraq,
    "ie" => Region::Ireland,
    "im" => Region::IsleOfMan,
    "il" => Region::Israel,
    "it" => Region::Italy,
    "jm" => Region::Jamaica,
    "jp" => Region::Japan,
    "je" => Region::Jersey,
    "jo" => Region::Jordan,
    "kz" => Region::Kazakhstan,
    "ke" => Region::Kenya,
    "ki" => Region::Kiribati,
    "xk" => Region::Kosovo,
    "kw" => Region::Kuwait,
    "kg" => Region::Kyrgyzstan,
    "la" => Region::Laos,
    "lv" => Region::Latvia,
    "lb" => Region::Lebanon,
    "ls" => Region::Lesotho,
    "lr" => Region::Liberia,
    "ly" => Region::Libya,
    "li" => Region::Liechtenstein,
    "lt" => Region::Lithuania,
    "lu" => Region::Luxembourg,
    "mo" => Region::Macao,
    "mg" => Region::Madagascar,
    "mw" => Region::Malawi,
    "my" => Region::Malaysia,
    "mv" => Region::Maldives,
    "ml" => Region::Mali,
    "mt" => Region::Malta,
    "mh" => Region::MarshallIslands,
    "mq" => Region::Martinique,
    "mr" => Region::Mauritania,
    "mu" => Region::Mauritius,
    "yt" => Region::Mayotte,
    "mx" => Region::Mexico,
    "fm" => Region::Micronesia,
    "md" => Region::Moldova,
    "mc" => Region::Monaco,
    "mn" => Region::Mongolia,
    "me" => Region::Montenegro,
    "ms" => Region::Montserrat,
    "ma" => Region::Morocco,
    "mz" => Region::Mozambique,
    "mm" => Region::Myanmar,
    "na" => Region::Namibia,
    "nr" => Region::Nauru,
    "np" => Region::Nepal,
    "nl" => Region::Netherlands,
    "nc" => Region::NewCaledonia,
    "nz" => Region::NewZealand,
    "ni" => Region::Nicaragua,
    "ne" => Region::Niger,
    "ng" => Region::Nigeria,
    "nu" => Region::Niue,
    "nf" => Region::NorfolkIsland,
    "kp" => Region::NorthKorea,
    "mk" => Region::NorthMacedonia,
    "mp" => Region::NorthernMarianaIslands,
    "no" => Region::Norway,
    "om" => Region::Oman,
    "pk" => Region::Pakistan,
    "pw" => Region::Palau,
    "ps" => Region::Palestine,
    "pa" => Region::Panama,
    "pg" => Region::PapuaNewGuinea,
    "py" => Region::Paraguay,
    "pe" => Region::Peru,
    "ph" => Region::Philippines,
    "pn" => Region::PitcairnIslands,
    "pl" => Region::Poland,
    "pt" => Region::Portugal,
    "pr" => Region::PuertoRico,
    "qa" => Region::Qatar,
    "ro" => Region::Romania,
    "ru" => Region::Russia,
    "rw" => Region::Rwanda,
    "re" => Region::Reunion,
    "ws" => Region::Samoa,
    "sm" => Region::SanMarino,
    "sa" => Region::SaudiArabia,
    "sn" => Region::Senegal,
    "rs" => Region::Serbia,
    "sc" => Region::Seychelles,
    "sl" => Region::SierraLeone,
    "sg" => Region::Singapore,
    "sx" => Region::SintMaarten,
    "sk" => Region::Slovakia,
    "si" => Region::Slovenia,
    "sb" => Region::SolomonIslands,
    "so" => Region::Somalia,
    "za" => Region::SouthAfrica,
    "gs" => Region::SouthGeorgiaAndTheSouthSandwichIslands,
    "kr" => Region::SouthKorea,
    "ss" => Region::SouthSudan,
    "es" => Region::Spain,
    "lk" => Region::SriLanka,
    "bl" => Region::StBarthelemy,
    "sh" => Region::StHelena,
    "kn" => Region::StKittsAndNevis,
    "lc" => Region::StLucia,
    "mf" => Region::StMartin,
    "pm" => Region::StPierreAndMiquelon,
    "vc" => Region::StVincentAndGrenadines,
    "sd" => Region::Sudan,
    "sr" => Region::Suriname,
    "sj" => Region::SvalbardAndJanMayen,
    "se" => Region::Sweden,
    "ch" => Region::Switzerland,
    "sy" => Region::Syria,
    "st" => Region::SaoTomeAndPrincipe,
    "tw" => Region::Taiwan,
    "tj" => Region::Tajikistan,
    "tz" => Region::Tanzania,
    "th" => Region::Thailand,
    "tl" => Region::TimorLeste,
    "tg" => Region::Togo,
    "tk" => Region::Tokelau,
    "to" => Region::Tonga,
    "tt" => Region::TrinidadAndTobago,
    "ta" => Region::TristanDaCunha,
    "tn" => Region::Tunisia,
    "tr" => Region::Turkey,
    "tm" => Region::Turkmenistan,
    "tc" => Region::TurksAndCaicosIslands,
    "tv" => Region::Tuvalu,
    "um" => Region::USOutlyingIslands,
    "vi" => Region::USVirginIslands,
    "ug" => Region::Uganda,
    "ua" => Region::Ukraine,
    "ae" => Region::UnitedArabEmirates,
    "co.uk" => Region::UnitedKingdom,
    "us" => Region::UnitedStates,
    "uy" => Region::Uruguay,
    "uz" => Region::Uzbekistan,
    "vu" => Region::Vanuatu,
    "va" => Region::VaticanCity,
    "ve" => Region::Venezuela,
    "vn" => Region::Vietnam,
    "wf" => Region::WallisAndFutuna,
    "eh" => Region::WesternSahara,
    "ye" => Region::Yemen,
    "zm" => Region::Zambia,
    "zw" => Region::Zimbabwe,
    "ax" => Region::AlandIslands,
};

// -----------------------------------------------------------------------------

impl std::convert::TryFrom<&str> for Region {
    // Error definitions are contained in the `google_maps\src\error.rs` module.
    type Error = crate::error::Error;
    /// Gets a `Region` enum from a `String` that contains a supported
    /// [region](https://developers.google.com/maps/coverage) code.
    fn try_from(region_code: &str) -> Result<Region, Error> {
        REGIONS_BY_CODE
            .get(region_code)
            .cloned()
            .ok_or_else(|| Error::InvalidRegionCode(region_code.to_string()))
    } // fn
} // impl

impl std::default::Default for Region {
    /// Returns a reasonable default variant for the `Region` enum type.
    fn default() -> Self {
        Region::UnitedStates
    } // fn
} // impl

impl std::fmt::Display for Region {
    /// Formats a `Region` enum into a string that is presentable to the end
    /// user.
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Region::Afghanistan => write!(f, "Afghanistan"),
            Region::Albania => write!(f, "Albania"),
            Region::Algeria => write!(f, "Algeria"),
            Region::AmericanSamoa => write!(f, "American Samoa"),
            Region::Andorra => write!(f, "Andorra"),
            Region::Angola => write!(f, "Angola"),
            Region::Anguilla => write!(f, "Anguilla"),
            Region::Antarctica => write!(f, "Antarctica"),
            Region::AntiguaAndBarbuda => write!(f, "Antigua & Barbuda"),
            Region::Argentina => write!(f, "Argentina"),
            Region::Armenia => write!(f, "Armenia"),
            Region::Aruba => write!(f, "Aruba"),
            Region::AscensionIsland => write!(f, "Ascension Island"),
            Region::Australia => write!(f, "Australia"),
            Region::Austria => write!(f, "Austria"),
            Region::Azerbaijan => write!(f, "Azerbaijan"),
            Region::Bahamas => write!(f, "Bahamas"),
            Region::Bahrain => write!(f, "Bahrain"),
            Region::Bangladesh => write!(f, "Bangladesh"),
            Region::Barbados => write!(f, "Barbados"),
            Region::Belarus => write!(f, "Belarus"),
            Region::Belgium => write!(f, "Belgium"),
            Region::Belize => write!(f, "Belize"),
            Region::Benin => write!(f, "Benin"),
            Region::Bermuda => write!(f, "Bermuda"),
            Region::Bhutan => write!(f, "Bhutan"),
            Region::Bolivia => write!(f, "Bolivia"),
            Region::BosniaAndHerzegovina => write!(f, "Bosnia & Herzegovina"),
            Region::Botswana => write!(f, "Botswana"),
            Region::BouvetIsland => write!(f, " Bouvet Island"),
            Region::Brazil => write!(f, "Brazil"),
            Region::BritishIndianOceanTerritory => write!(f, "British Indian Ocean Territory"),
            Region::BritishVirginIslands => write!(f, "British Virgin Islands"),
            Region::Brunei => write!(f, "Brunei"),
            Region::Bulgaria => write!(f, "Bulgaria"),
            Region::BurkinaFaso => write!(f, "Burkina Faso"),
            Region::Burundi => write!(f, "Burundi"),
            Region::Cambodia => write!(f, "Cambodia"),
            Region::Cameroon => write!(f, "Cameroon"),
            Region::Canada => write!(f, "Canada"),
            Region::CanaryIslands => write!(f, "Canary Islands"),
            Region::CapeVerde => write!(f, "Cape Verde"),
            Region::CaribbeanNetherlands => write!(f, "Caribbean Netherlands"),
            Region::CaymanIslands => write!(f, "Cayman Islands"),
            Region::CentralAfricanRepublic => write!(f, "Central African Republic"),
            Region::CeutaAndMelilla => write!(f, "Ceuta & Melilla"),
            Region::Chad => write!(f, "Chad"),
            Region::Chile => write!(f, "Chile"),
            Region::China => write!(f, "China"),
            Region::ChristmasIsland => write!(f, "Christmas Island"),
            Region::ClippertonIsland => write!(f, "Clipperton Island"),
            Region::CocosKeelingIslands => write!(f, "Cocos (Keeling) Islands"),
            Region::Colombia => write!(f, "Colombia"),
            Region::Comoros => write!(f, "Comoros"),
            Region::CongoBrazzaville => write!(f, "Congo - Brazzaville"),
            Region::CongoKinshasa => write!(f, "Congo - Kinshasa"),
            Region::CookIslands => write!(f, "Cook Islands"),
            Region::CostaRica => write!(f, "Costa Rica"),
            Region::Croatia => write!(f, "Croatia"),
            Region::Cuba => write!(f, "Cuba"),
            Region::Curacao => write!(f, "Curaçao"),
            Region::Cyprus => write!(f, "Cyprus"),
            Region::Czechia => write!(f, "Czechia"),
            Region::CotedIvoire => write!(f, "Côte d’Ivoire"),
            Region::Denmark => write!(f, "Denmark"),
            Region::DiegoGarcia => write!(f, "Diego Garcia"),
            Region::Djibouti => write!(f, "Djibouti"),
            Region::Dominica => write!(f, "Dominica"),
            Region::DominicanRepublic => write!(f, "Dominican Republic"),
            Region::Ecuador => write!(f, "Ecuador"),
            Region::Egypt => write!(f, "Egypt"),
            Region::ElSalvador => write!(f, "El Salvador"),
            Region::EquatorialGuinea => write!(f, "Equatorial Guinea"),
            Region::Eritrea => write!(f, "Eritrea"),
            Region::Estonia => write!(f, "Estonia"),
            Region::Eswatini => write!(f, "Eswatini"),
            Region::Ethiopia => write!(f, "Ethiopia"),
            Region::FalklandIslands => write!(f, "Falkland Islands (Islas Malvinas)"),
            Region::FaroeIslands => write!(f, "Faroe Islands"),
            Region::Fiji => write!(f, "Fiji"),
            Region::Finland => write!(f, "Finland"),
            Region::France => write!(f, "France"),
            Region::FrenchGuiana => write!(f, "French Guiana"),
            Region::FrenchPolynesia => write!(f, "French Polynesia"),
            Region::FrenchSouthernTerritories => write!(f, "French Southern Territories"),
            Region::Gabon => write!(f, "Gabon"),
            Region::Gambia => write!(f, "Gambia"),
            Region::Georgia => write!(f, "Georgia"),
            Region::Germany => write!(f, "Germany"),
            Region::Ghana => write!(f, "Ghana"),
            Region::Gibraltar => write!(f, "Gibraltar"),
            Region::Greece => write!(f, "Greece"),
            Region::Greenland => write!(f, "Greenland"),
            Region::Grenada => write!(f, "Grenada"),
            Region::Guadeloupe => write!(f, "Guadeloupe"),
            Region::Guam => write!(f, "Guam"),
            Region::Guatemala => write!(f, "Guatemala"),
            Region::Guernsey => write!(f, "Guernsey"),
            Region::Guinea => write!(f, "Guinea"),
            Region::GuineaBissau => write!(f, "Guinea-Bissau"),
            Region::Guyana => write!(f, "Guyana"),
            Region::Haiti => write!(f, "Haiti"),
            Region::HeardAndMcDonaldIslands => write!(f, "Heard & McDonald Islands"),
            Region::Honduras => write!(f, "Honduras"),
            Region::HongKong => write!(f, "Hong Kong"),
            Region::Hungary => write!(f, "Hungary"),
            Region::Iceland => write!(f, "Iceland"),
            Region::India => write!(f, "India"),
            Region::Indonesia => write!(f, "Indonesia"),
            Region::Iran => write!(f, "Iran"),
            Region::Iraq => write!(f, "Iraq"),
            Region::Ireland => write!(f, "Ireland"),
            Region::IsleOfMan => write!(f, "Isle of Man"),
            Region::Israel => write!(f, "Israel"),
            Region::Italy => write!(f, "Italy"),
            Region::Jamaica => write!(f, "Jamaica"),
            Region::Japan => write!(f, "Japan"),
            Region::Jersey => write!(f, "Jersey"),
            Region::Jordan => write!(f, "Jordan"),
            Region::Kazakhstan => write!(f, "Kazakhstan"),
            Region::Kenya => write!(f, "Kenya"),
            Region::Kiribati => write!(f, "Kiribati"),
            Region::Kosovo => write!(f, "Kosovo"),
            Region::Kuwait => write!(f, "Kuwait"),
            Region::Kyrgyzstan => write!(f, "Kyrgyzstan"),
            Region::Laos => write!(f, "Laos"),
            Region::Latvia => write!(f, "Latvia"),
            Region::Lebanon => write!(f, "Lebanon"),
            Region::Lesotho => write!(f, "Lesotho"),
            Region::Liberia => write!(f, "Liberia"),
            Region::Libya => write!(f, "Libya"),
            Region::Liechtenstein => write!(f, "Liechtenstein"),
            Region::Lithuania => write!(f, "Lithuania"),
            Region::Luxembourg => write!(f, "Luxembourg"),
            Region::Macao => write!(f, "Macao"),
            Region::Madagascar => write!(f, "Madagascar"),
            Region::Malawi => write!(f, "Malawi"),
            Region::Malaysia => write!(f, "Malaysia"),
            Region::Maldives => write!(f, "Maldives"),
            Region::Mali => write!(f, "Mali"),
            Region::Malta => write!(f, "Malta"),
            Region::MarshallIslands => write!(f, "Marshall Islands"),
            Region::Martinique => write!(f, "Martinique"),
            Region::Mauritania => write!(f, "Mauritania"),
            Region::Mauritius => write!(f, "Mauritius"),
            Region::Mayotte => write!(f, "Mayotte"),
            Region::Mexico => write!(f, "Mexico"),
            Region::Micronesia => write!(f, "Micronesia"),
            Region::Moldova => write!(f, "Moldova"),
            Region::Monaco => write!(f, "Monaco"),
            Region::Mongolia => write!(f, "Mongolia"),
            Region::Montenegro => write!(f, "Montenegro"),
            Region::Montserrat => write!(f, "Montserrat"),
            Region::Morocco => write!(f, "Morocco"),
            Region::Mozambique => write!(f, "Mozambique"),
            Region::Myanmar => write!(f, "Myanmar (Burma)"),
            Region::Namibia => write!(f, "Namibia"),
            Region::Nauru => write!(f, "Nauru"),
            Region::Nepal => write!(f, "Nepal"),
            Region::Netherlands => write!(f, "Netherlands"),
            Region::NewCaledonia => write!(f, "New Caledonia"),
            Region::NewZealand => write!(f, "New Zealand"),
            Region::Nicaragua => write!(f, "Nicaragua"),
            Region::Niger => write!(f, "Niger"),
            Region::Nigeria => write!(f, "Nigeria"),
            Region::Niue => write!(f, "Niue"),
            Region::NorfolkIsland => write!(f, "Norfolk Island"),
            Region::NorthKorea => write!(f, "North Korea"),
            Region::NorthMacedonia => write!(f, "North Macedonia"),
            Region::NorthernMarianaIslands => write!(f, "Northern Mariana Islands"),
            Region::Norway => write!(f, "Norway"),
            Region::Oman => write!(f, "Oman"),
            Region::Pakistan => write!(f, "Pakistan"),
            Region::Palau => write!(f, "Palau"),
            Region::Palestine => write!(f, "Palestine"),
            Region::Panama => write!(f, "Panama"),
            Region::PapuaNewGuinea => write!(f, "Papua New Guinea"),
            Region::Paraguay => write!(f, "Paraguay"),
            Region::Peru => write!(f, "Peru"),
            Region::Philippines => write!(f, "Philippines"),
            Region::PitcairnIslands => write!(f, "Pitcairn Islands"),
            Region::Poland => write!(f, "Poland"),
            Region::Portugal => write!(f, "Portugal"),
            Region::PuertoRico => write!(f, "Puerto Rico"),
            Region::Qatar => write!(f, "Qatar"),
            Region::Romania => write!(f, "Romania"),
            Region::Russia => write!(f, "Russia"),
            Region::Rwanda => write!(f, "Rwanda"),
            Region::Reunion => write!(f, "Réunion"),
            Region::Samoa => write!(f, "Samoa"),
            Region::SanMarino => write!(f, "San Marino"),
            Region::SaudiArabia => write!(f, "Saudi Arabia"),
            Region::Senegal => write!(f, "Senegal"),
            Region::Serbia => write!(f, "Serbia"),
            Region::Seychelles => write!(f, "Seychelles"),
            Region::SierraLeone => write!(f, "Sierra Leone"),
            Region::Singapore => write!(f, "Singapore"),
            Region::SintMaarten => write!(f, "Sint Maarten"),
            Region::Slovakia => write!(f, "Slovakia"),
            Region::Slovenia => write!(f, "Slovenia"),
            Region::SolomonIslands => write!(f, "Solomon Islands"),
            Region::Somalia => write!(f, "Somalia"),
            Region::SouthAfrica => write!(f, "South Africa"),
            Region::SouthGeorgiaAndTheSouthSandwichIslands => write!(f, "South Georgia & South Sandwich Islands"),
            Region::SouthKorea => write!(f, "South Korea"),
            Region::SouthSudan => write!(f, "South Sudan"),
            Region::Spain => write!(f, "Spain"),
            Region::SriLanka => write!(f, "Sri Lanka"),
            Region::StBarthelemy => write!(f, "St. Barthélemy"),
            Region::StHelena => write!(f, "St. Helena"),
            Region::StKittsAndNevis => write!(f, "St. Kitts & Nevis"),
            Region::StLucia => write!(f, "St. Lucia"),
            Region::StMartin => write!(f, "St. Martin"),
            Region::StPierreAndMiquelon => write!(f, "St. Pierre & Miquelon"),
            Region::StVincentAndGrenadines => write!(f, "St. Vincent & Grenadines"),
            Region::Sudan => write!(f, "Sudan"),
            Region::Suriname => write!(f, "Suriname"),
            Region::SvalbardAndJanMayen => write!(f, "Svalbard & Jan Mayen"),
            Region::Sweden => write!(f, "Sweden"),
            Region::Switzerland => write!(f, "Switzerland"),
            Region::Syria => write!(f, "Syria"),
            Region::SaoTomeAndPrincipe => write!(f, "São Tomé & Príncipe"),
            Region::Taiwan => write!(f, "Taiwan"),
            Region::Tajikistan => write!(f, "Tajikistan"),
            Region::Tanzania => write!(f, "Tanzania"),
            Region::Thailand => write!(f, "Thailand"),
            Region::TimorLeste => write!(f, "Timor-Leste"),
            Region::Togo => write!(f, "Togo"),
            Region::Tokelau => write!(f, "Tokelau"),
            Region::Tonga => write!(f, "Tonga"),
            Region::TrinidadAndTobago => write!(f, "Trinidad & Tobago"),
            Region::TristanDaCunha => write!(f, "Tristan da Cunha"),
            Region::Tunisia => write!(f, "Tunisia"),
            Region::Turkey => write!(f, "Turkey"),
            Region::Turkmenistan => write!(f, "Turkmenistan"),
            Region::TurksAndCaicosIslands => write!(f, "Turks & Caicos Islands"),
            Region::Tuvalu => write!(f, "Tuvalu"),
            Region::USOutlyingIslands => write!(f, "U.S. Outlying Islands"),
            Region::USVirginIslands => write!(f, "U.S. Virgin Islands"),
            Region::Uganda => write!(f, "Uganda"),
            Region::Ukraine => write!(f, "Ukraine"),
            Region::UnitedArabEmirates => write!(f, "United Arab Emirates"),
            Region::UnitedKingdom => write!(f, "United Kingdom"),
            Region::UnitedStates => write!(f, "United States"),
            Region::Uruguay => write!(f, "Uruguay"),
            Region::Uzbekistan => write!(f, "Uzbekistan"),
            Region::Vanuatu => write!(f, "Vanuatu"),
            Region::VaticanCity => write!(f, "Vatican City"),
            Region::Venezuela => write!(f, "Venezuela"),
            Region::Vietnam => write!(f, "Vietnam"),
            Region::WallisAndFutuna => write!(f, "Wallis & Futuna"),
            Region::WesternSahara => write!(f, "Western Sahara"),
            Region::Yemen => write!(f, "Yemen"),
            Region::Zambia => write!(f, "Zambia"),
            Region::Zimbabwe => write!(f, "Zimbabwe"),
            Region::AlandIslands => write!(f, "Åland Islands"),
        } // match
    } // fn
} // impl