use crate::places_new::LocalizedText;

// -------------------------------------------------------------------------------------------------
//
/// A summary of points of interest near a place.
///
/// Neighborhood summaries provide AI-generated overviews of the surrounding area, highlighting
/// notable places, attractions, and characteristics of the neighborhood. These summaries help
/// users understand the local context and what makes an area interesting or notable.
///
/// The content is generated using Gemini AI capabilities and is regularly updated to reflect
/// current information about the neighborhood.
#[derive(
    //std
    Clone,
    Debug,
    Eq,
    Hash,
    PartialEq,
    // getset
    getset::Getters,
    // serde
    serde::Deserialize,
    serde::Serialize
)]
#[serde(rename_all = "camelCase")]
pub struct NeighborhoodSummary {
    /// An overview summary of the neighborhood.
    ///
    /// Provides a high-level description of the neighborhood, including notable characteristics,
    /// popular attractions, and general atmosphere. Generated by AI to give users a quick
    /// understanding of what makes this area distinctive.
    #[getset(get = "pub")]
    pub overview: LocalizedText,

    /// A detailed description of the neighborhood.
    ///
    /// Contains more comprehensive information about the neighborhood, including specific points
    /// of interest, local amenities, and detailed characteristics that help users understand
    /// the area's unique features and appeal.
    #[getset(get = "pub")]
    pub description: LocalizedText,

    /// A link where users can flag a problem with the summary.
    ///
    /// Provides a URL where users can report issues with the AI-generated content, such as
    /// inaccurate information or inappropriate content, enabling quality control and improvement
    /// of the summary system.
    #[getset(get = "pub")]
    pub flag_content_uri: url::Url,

    /// The AI disclosure message indicating the content source.
    ///
    /// Contains localized text such as "Summarized with Gemini" to inform users that the content
    /// was generated using AI technology. Appears in the language specified in the request when
    /// available.
    #[getset(get = "pub")]
    pub disclosure_text: LocalizedText,
}